window.MAELIE_PRODUCTS = [
  {
    id: 1,
    slug: "robe-eclat",
    name: "Robe Éclat",
    cat: "Mode",
    price: 69.9,
    old: 89.9,
    img: "img/produits/robe-eclat.svg",
    badge: "Bestseller",
    new: true,
    rating: 4.9,
    reviews: 128,
    desc: "Une robe fluide et lumineuse, pensée pour accompagner les journées comme les soirées.",
  },
  {
    id: 2,
    slug: "bracelet-luna",
    name: "Bracelet Luna",
    cat: "Bijoux",
    price: 29.9,
    img: "img/produits/bracelet-luna.svg",
    badge: "Nouveau",
    new: true,
    rating: 4.8,
    reviews: 86,
    desc: "Un bracelet délicat qui apporte une touche lumineuse à toutes vos tenues.",
  },
  {
    id: 3,
    slug: "collier-perle",
    name: "Collier Perlé",
    cat: "Bijoux",
    price: 34.9,
    old: 44.9,
    img: "img/produits/collier-perle.svg",
    badge: "-22%",
    rating: 4.8,
    reviews: 74,
    desc: "Un collier raffiné aux lignes intemporelles, facile à porter au quotidien.",
  },
  {
    id: 4,
    slug: "bague-rose",
    name: "Bague Rose",
    cat: "Bijoux",
    price: 24.9,
    img: "img/produits/bague-rose.svg",
    rating: 4.7,
    reviews: 61,
    desc: "Une bague fine et lumineuse pour compléter votre style avec subtilité.",
  },
  {
    id: 5,
    slug: "bougie-fleurie",
    name: "Bougie Fleurie",
    cat: "Maison",
    price: 24.9,
    old: 29.9,
    img: "img/produits/bougie-fleurie.svg",
    badge: "Coup de cœur",
    new: true,
    rating: 4.9,
    reviews: 112,
    desc: "Une bougie parfumée aux notes florales pour créer une atmosphère chaleureuse.",
  },
  {
    id: 6,
    slug: "bougie-vanille",
    name: "Bougie Vanille",
    cat: "Maison",
    price: 19.9,
    img: "img/produits/bougie-vanille.svg",
    rating: 4.7,
    reviews: 48,
    desc: "Une senteur vanillée douce et réconfortante pour une ambiance cocooning.",
  },
  {
    id: 7,
    slug: "coffret-elegance",
    name: "Coffret Élégance",
    cat: "Coffrets",
    price: 59.9,
    old: 69.9,
    img: "img/produits/coffret-elegance.svg",
    badge: "Idée cadeau",
    new: true,
    rating: 4.9,
    reviews: 95,
    desc: "Un coffret soigneusement composé pour offrir une parenthèse élégante et parfumée.",
  },
  {
    id: 8,
    slug: "diffuseur-floral",
    name: "Diffuseur Floral",
    cat: "Maison",
    price: 39.9,
    old: 49.9,
    img: "img/produits/diffuseur-floral.svg",
    badge: "-20%",
    rating: 4.8,
    reviews: 57,
    desc: "Un diffuseur floral discret qui parfume délicatement votre intérieur.",
  },
  {
    id: 9,
    slug: "chemise-satin",
    name: "Chemise Satin",
    cat: "Mode",
    price: 44.9,
    img: "img/produits/chemise-satin.svg",
    badge: "Nouveau",
    new: true,
    rating: 4.6,
    reviews: 39,
    desc: "Une chemise satinée au tombé souple, idéale pour composer une silhouette chic.",
  },
  {
    id: 10,
    slug: "pochette-nacre",
    name: "Pochette Nacre",
    cat: "Accessoires",
    price: 32.9,
    old: 39.9,
    img: "img/produits/pochette-nacre.svg",
    badge: "-18%",
    rating: 4.7,
    reviews: 43,
    desc: "Une pochette compacte et élégante pour garder l’essentiel à portée de main.",
  },
  {
    id: 11,
    slug: "bougie-coton",
    name: "Bougie Coton",
    cat: "Maison",
    price: 22.9,
    img: "img/produits/bougie-coton.svg",
    badge: "Nouveau",
    new: true,
    rating: 4.6,
    reviews: 31,
    desc: "Une fragrance propre et douce inspirée du linge fraîchement lavé.",
  },
  {
    id: 12,
    slug: "coffret-douceur",
    name: "Coffret Douceur",
    cat: "Coffrets",
    price: 69.9,
    old: 79.9,
    img: "img/produits/coffret-douceur.svg",
    badge: "Cadeau",
    rating: 4.9,
    reviews: 68,
    desc: "Une sélection généreuse pour célébrer les petits et grands moments.",
  },
  {
    id: 13,
    slug: "sac-maelie",
    name: "Sac Maelie",
    cat: "Accessoires",
    price: 54.9,
    img: "img/produits/sac-maelie.svg",
    badge: "Signature",
    new: true,
    rating: 4.8,
    reviews: 52,
    desc: "Un sac souple et structuré qui accompagne facilement vos journées.",
  },
  {
    id: 14,
    slug: "boucles-nacre",
    name: "Boucles Nacre",
    cat: "Bijoux",
    price: 27.9,
    img: "img/produits/boucles-nacre.svg",
    rating: 4.8,
    reviews: 44,
    desc: "Des boucles délicates aux reflets nacrés pour illuminer le visage.",
  },
  {
    id: 15,
    slug: "parfum-rose",
    name: "Brume Rose",
    cat: "Beauté",
    price: 36.9,
    old: 42.9,
    img: "img/produits/parfum-rose.svg",
    badge: "Nouveau",
    new: true,
    rating: 4.9,
    reviews: 37,
    desc: "Une brume légère aux notes florales et poudrées, signature de la maison.",
  },
  {
    id: 16,
    slug: "porte-cartes",
    name: "Porte-cartes Nacre",
    cat: "Accessoires",
    price: 21.9,
    img: "img/produits/porte-cartes.svg",
    rating: 4.6,
    reviews: 29,
    desc: "Un petit essentiel élégant pour organiser vos cartes avec simplicité.",
  },
  {
    id: 17,
    slug: "echarpe-douceur",
    name: "Écharpe Douceur",
    cat: "Mode",
    price: 39.9,
    img: "img/produits/echarpe-douceur.svg",
    rating: 4.7,
    reviews: 33,
    desc: "Une écharpe légère et enveloppante pour les journées fraîches.",
  },
  {
    id: 18,
    slug: "set-rituel",
    name: "Set Rituel Maison",
    cat: "Maison",
    price: 49.9,
    old: 59.9,
    img: "img/produits/set-rituel.svg",
    badge: "Coup de cœur",
    rating: 4.9,
    reviews: 47,
    desc: "Un trio parfumé imaginé pour créer votre rituel douceur à la maison.",
  },
];
