(() => {
  const root = document.querySelector('[data-product-page]'); if (!root) return;
  const slug = new URLSearchParams(location.search).get('slug') || 'robe-eclat';
  const p = MAELIE_PRODUCTS.find(x => x.slug === slug) || MAELIE_PRODUCTS[0];
  document.title = `${p.name} — MAELIE`;
  root.innerHTML = `<div class="breadcrumbs"><a href="index.html">Accueil</a><span>›</span><a href="boutique.html">Boutique</a><span>›</span><span>${p.name}</span></div>
  <div class="product-detail"><div class="product-visual"><img src="${p.img}" alt="${p.name}"></div><div class="product-copy"><span class="eyebrow">${p.cat}${p.badge ? ` · ${p.badge}` : ''}</span><h1>${p.name}</h1><div class="stars">${MAELIE.stars(p.rating)} <span class="muted">${p.rating}/5 · ${p.reviews} avis</span></div><div class="detail-price">${MAELIE.money(p.price)} ${p.old ? `<span class="old">${MAELIE.money(p.old)}</span>` : ''}</div><p class="detail-desc">${p.desc}</p><div class="detail-actions"><div class="quantity"><button data-dec type="button">−</button><span data-q>1</span><button data-inc type="button">+</button></div><button class="btn btn-primary" data-add-product type="button">Ajouter au panier</button><button class="icon-btn" data-fav="${p.id}" type="button">${MAELIE.favs().includes(p.id) ? '♥' : '♡'}</button></div><div class="info-list"><div class="info-item"><strong>Livraison</strong><br>3 à 5 jours ouvrés</div><div class="info-item"><strong>Retours</strong><br>14 jours pour changer d'avis</div><div class="info-item"><strong>Qualité</strong><br>Choisi avec soin par MAELIE</div><div class="info-item"><strong>Emballage</strong><br>Préparé avec attention</div></div></div></div>
  <section class="section related"><div class="section-head"><div><span class="eyebrow">Vous aimerez aussi</span><h2>Dans le même esprit</h2></div><a class="btn btn-outline" href="boutique.html?cat=${encodeURIComponent(p.cat)}">Voir la catégorie</a></div><div class="product-grid">${MAELIE_PRODUCTS.filter(x=>x.id!==p.id&&x.cat===p.cat).slice(0,4).map(MAELIE.card).join('')}</div></section>`;
  let q=1; root.querySelector('[data-inc]').onclick=()=>{q=Math.min(99,q+1);root.querySelector('[data-q]').textContent=q}; root.querySelector('[data-dec]').onclick=()=>{q=Math.max(1,q-1);root.querySelector('[data-q]').textContent=q}; root.querySelector('[data-add-product]').onclick=()=>MAELIE.add(p.id,q);
})();
